**Program 1**:

**Problem Statement**:

Take a 5x6 NumPy array and mirror the 5x6 NumPy array using loop.

In [1]:
import numpy as np

# 5x6 array
arr = np.array(
    [
        [1, 2, 3, 4, 5, 6],
        [7, 8, 9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
    ]
)

rows, cols = arr.shape

mirrored = arr.copy()

for i in range(rows):
    for j in range(cols // 2):
        temp = mirrored[i][j]
        mirrored[i][j] = mirrored[i][cols - 1 - j]
        mirrored[i][cols - 1 - j] = temp

print("Original:")
print(arr)

print("Mirrored:")
print(mirrored)


Original:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Mirrored:
[[ 6  5  4  3  2  1]
 [12 11 10  9  8  7]
 [18 17 16 15 14 13]
 [24 23 22 21 20 19]
 [30 29 28 27 26 25]]
