1. Take a 6x6 NumPy array apply convolution operation of the array. Use zero pading and consider a 3x3 mask/kernel for convolution (with and without built in function). Show both input and output array NumPy array into an image and show them side by side in a subplot with a title

In [ ]:
import numpy as np


img = np.array([
    [1, 8, 8, 0, 7],
    [4, 7, 9, 5, 7],
    [5, 4, 6, 8, 6],
    [4, 2, 0, 1, 5],
    [0, 1, 0, 2, 0]
])

k = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1]
]) / 9

img = np.pad(img, 1, "constant", constant_values=0)

out = img.copy()

for i in range(1, img.shape[0]-1):
  for j in range(1, img.shape[1]-1):
    out[i, j] = round(np.sum(img[i-1:i+2, j-1:j+2] * k))

out = out[1:out.shape[0]-1, 1:out.shape[1]-1]

print(out)

[[2 4 4 4 2]
 [3 6 6 6 4]
 [3 5 5 5 4]
 [2 2 3 3 2]
 [1 1 1 1 1]]


In [30]:
import cv2
import numpy as np

image = cv2.imread('./a.jpg')
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

k = np.ones((3, 3)) / 9

# pad the correct image
img = np.pad(image_gray, 1, mode="constant", constant_values=0)

out = np.zeros_like(image_gray)

for i in range(1,image_gray.shape[0]-1):
    for j in range(1,image_gray.shape[1]-1):
        region = img[i-1:i+2, j-1:j+2]
        out[i, j] = np.sum(region * k)

out = out[1:out.shape[0]-1, 1:out.shape[1]-1]

print(out)

[[ 70 105 105 ...  84  94 104]
 [105 158 158 ... 125 134 142]
 [105 158 158 ... 120 116 111]
 ...
 [ 36  52  52 ...  56  57  59]
 [ 34  49  50 ...  56  60  68]
 [ 32  46  49 ...  56  65  77]]


2. Take an 8-bit grayscale image and apply smoothing operation by using mean filter (with and without built in image smoothing function). Show both input and output image side by side in a subplot with a title.

3. Take an 8-bit grayscale and apply smoothing operation by using weighted averaging filter (with and without built in smoothing function). Show both input and output image side by side in a subplot with a title)

4. Take an 8-bit grayscale image and apply smoothing operation by using gaussian filter (with and without)